Feat/create supergraph by gateway
qest-cz/gql-federation-sample pull request #9
Opened 2022-08-22 11:52 UTC by mikesjcz

2022-08-22 13:58 UTC, kinapets requested changes

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/articleapp/src/resolvers/article/index.ts
> +    getAllArticles(_, __, c: Context) {
jen pro tip lepsi rovnou vytahnout ty dataSources nez tam mit cecko 


{dataSources}: Context

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +  setInterval(restartServer, Number(process.env.INTERVAL))
hele super ale neming nic moc, z restart server bych cekal ze se fakt restartne, ale tady dojde jen k checknuti jestli se ma restartnout, zkus to udelat vic clear

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +import { readFileSync } from 'fs';
kde se pouziva tohle? pls pridat eslint pravidlo, no  unused

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +let server: ApolloServer = null
nechces tyhle radky 10-12 zabalit do nejake classky? aby tady nebyly ty lety? ale byla to proste vsechno stavova vec? a mohl by tam byt i restart server

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/interfaces.ts
> +export interface SupergraphStorageManager{
❓ tady se dost divim ze to ma jenom get a zadnej insert.... 

jak potom do te storage vlozis novej graph?

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/interfaces.ts
> +    getSupergraph(): Promise<Buffer>
tady bych cekal ze to bude vracet string coz? ten Buffer mi prijde dost low-level

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/local-storage-manager.ts
> +        return new Promise<Buffer>((resolve) => {
proc je tady tenhle Promise? to je zbytecne ne?

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/prisma-manager.ts
> +            const buff: Buffer = Buffer.from(file.file, "utf-8");
vidis zbytecne pak musis prevadet to schema na nejake buffer a potom se to jeste jednou deje zpatky

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/supergraph-services.ts
> +            resolve((fs.readFileSync(process.env.SUPERGRAPH_FILE)))
tady to asi neva ale radeji i tak pouzij radsi readFileSync 

jo tvl tak tady to nedava smysl ze mas nejakej resovle a to je synchroni fce to neni zadnej callback

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/supergraph-services.ts
> +export const tryCreatePartOfSupergraph = async() : Promise<Buffer> => {
tady mi uprimne chybi kde se to nahraje to te storage? jak se to dostane treba do te sqlky

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/supergraph-services.ts
> +    fs.unlink(path, (err) => {
tohle takz bude v tom promise api ne?

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/index.ts
> +export interface SupergraphManager {
jakto ze tady neni get

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/local-storage-manager.ts
> +        } catch (error) {
fuuuj prazdnej try catch

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/local-storage-manager.ts
> +        fsPromises.writeFile(process.env.SUPERGRAPH_FILE, newSuperGraph)
❗️ to plati vsude urcite nepouzivat takhle dole v implementaci process.env 

tohle je treba predat pres konfiguraci

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/prisma-manager.ts
> +                id: process.env.SUPERGRAPH_FILE_NAME
tady taky jo, process env

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/supergraph-services.ts
> +    const command: string = "rover supergraph compose --config " + process.env.SUPERGRAPH_CONFIG_YML + " > " + newFilePath
tady takz prosim

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/supergraph-services.ts
> +        checkAndRemoveCreatedFile(newFilePath)
tady by chtel nejakej await ne?

2022-08-22 13:58 UTC, kinapets commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/supergraph-services.ts
> +        throw new Error("Creating supergraph failed!")
tady skoda ze se ztrati ta informace co se stalo

2022-08-22 14:04 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/federation-gateway/src/services/interfaces.ts
> +export interface SupergraphStorageManager{
To řeší ta druhá aplikace. gateway si šahá jen pro supergraph, nic nezapisuje.

2022-08-23 09:02 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/articleapp/src/resolvers/article/index.ts
> +    getAllArticles(_, __, c: Context) {
opraveno

2022-08-23 09:03 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +  setInterval(restartServer, Number(process.env.INTERVAL))
předěláno do separe class

2022-08-23 09:03 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +import { readFileSync } from 'fs';
odstraněno

2022-08-23 09:03 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/federation-gateway/src/main.ts
> +let server: ApolloServer = null
předěláno, dáno do serverManager

2022-08-23 09:03 UTC, mikesjcz commented on monorepo/monorepo-ws/apps/update-supergraph-app/src/services/local-storage-manager.ts
> +        fsPromises.writeFile(process.env.SUPERGRAPH_FILE, newSuperGraph)
udělány config soubory

2022-08-24 10:45 UTC, kinapets approved these changes

2022-08-24 10:46 UTC, merged